### ISSUE TITLE
Document how components in nested routes work

### ISSUE THREAD

**Issue by maxmilton** [solidjs/solid-app-router#10]
This one threw me off for a while until I understood how it works. In the routes definition, when a route has children, its component must contain a `Route` component for those children to be rendered.

For example;

```jsx
import { Route, Router } from 'solid-app-router';
import { lazy } from 'solid-js';
import { render } from "solid-js/web";

const routes = [
  {
    path: '/my-page',
    component: lazy(() => import('./pages/my-page')),
  },
  {
    path: '/my-page/:slug',
    component: Route, // <-- this is what I was missing
    children: [
      {
        path: '/',
        component: lazy(() => import('./pages/my-page/[slug]')),
      },
      {
        path: '/sub-page',
        component: lazy(() => import('./pages/my-page/[slug]/sub-page')),
      },
    ],
  },
];

const App = () => (
  <Router routes={routes}>
    <Route />
  </Router>
);

render(App, document.getElementById('app'));
```

In the example I've used `Route` as the actual component but it's enough for the route's `component` to contain a `<Route />`.

It's obvious in retrospect but after using so many different router implementations over the years I wasn't sure if it was automagically injected or just how flexible nesting is.

> Note: I know there's no formal documentation yet, so this is just a tip for when you get to it!

**Comment by ryansolid** [comment]
Oh interesting. I never thought of using it that way although I guess it would work..

You can make a segment as deep as you want. With what you have I would have expected this:
```
const routes = [
  {
    path: '/my-page',
    component: lazy(() => import('./pages/my-page')),
  },
  {
    path: '/my-page/:slug',
    component: lazy(() => import('./pages/my-page/[slug]')),
  },
  {
     path: '/my-page/:slug/sub-page',
     component: lazy(() => import('./pages/my-page/[slug]/sub-page')),
  }
];
```
The reason for nesting is to re-use part of the page, like a header section. If you would just insert a Route component you are basically flattening it. The idea with nesting is that the header would create a `<Route>` and insert it's children there. But it would be for layout reasons. And then when you change the nested route the header doesn't re-render but the nested tabs do.

**Comment by MaxMilton** [comment]
That makes sense 👍🏼 

In my case I was experimenting with dynamically constructing the routes based on file system hierarchy so that's when I was tripped up. For manually constructed routes, definitely simpler structure is better.

**Comment by ryansolid** [comment]
Ok have done a bit better job with the documentation with the recent release.
