### ISSUE TITLE
Unexpected behavior with search params on non-root path

### ISSUE THREAD

**Issue by spsaucier** [solidjs/solid-app-router#101]
### ACTUAL:

`navigate('/?key=value')` from `/login` navigates to `/login?key=value`

### EXPECTED:

Just as `window.location.assign('/?key=value')` from `/login` navigates to `/?key=value`,

so `navigate('/?key=value')` from `/login` should navigate to `/?key=value`

**Comment by Genuifx** [comment]
![image](https://user-images.githubusercontent.com/10156994/167536064-df19364c-8766-452f-b58c-884085f3a819.png)

Ryan already fixed it at [here](https://github.com/solidjs/solid-app-router/commit/5670b53907712124adf8a8b771b34ad4364dd8f0#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351L26)

@rturnq why not close this issue
