### ISSUE TITLE
location.hash and location.query lack leading #/?

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid-app-router#103]
I feel like these are pretty nonstandard definitions of `search` and `hash` (throwing away the `?` and `#`).

https://github.com/solidjs/solid-app-router/blob/8dbd218b0d5cff9743ab892e115f50263b21bd9a/src/routing.ts#L212-L213 

In particular they don't match the web specs (`window.location` behaves very different from `useLocation()`), and it makes it hard to recreate URLs. As mentioned on Discord, might also be the cause for #101.

The downside to changing this is backward compatibility. But it may be worth it in the long run. At the least, I think this discrepancy should be documented.

**Comment by Jutanium** [comment]
oh wow, I definitely need to document this if it's staying!

**Comment by Genuifx** [comment]
#101 Just bug from resolvePath function, is not related to location that router created.

**Comment by edemaine** [comment]
It looks like this issue was fixed! (including in 0.4.1 release, possibly earlier)

https://github.com/solidjs/solid-app-router/blob/8b02817260ae185e2254a83c6e98307fbe8b4390/src/routing.ts#L229-L230

I'd like to remind the maintainers that it would be extremely helpful to have a CHANGELOG for this project. While I'm glad that this got fixed, it is a breaking change, and required me to adapt my code accordingly.
