### ISSUE TITLE
Strange removal of spaces in href attribute of <Link/>

### ISSUE THREAD

**Issue by titoBouzout** [solidjs/solid-app-router#112]
Stumble upon this curious case
```js
import { Link, useParams } from 'solid-app-router'

<Link href="/blog/bla bla bla"/>

// becomes 

<a href="/blog/blablabla"/>
```

I know folder/file/path names should be escaped, but in any case this shouldn't be happening. 

Found out is related to this change, the change on the regular expression at line 5  https://github.com/solidjs/solid-app-router/commit/6ce024ed88382d23a5fc6b83c80fa593d5f7b409

I'm not completely sure what the removal of the space is trying to achieve here.

A question if you don't mind, why the path doesn't gets escaped automatically?

Thanks!

**Comment by rturnq** [comment]
Looks like that string removal in the regex was inadvertent. This was a good find as we weren't properly handling spaces and other encoded characters in the path, search query and hash.

**Comment by titoBouzout** [comment]
Thank you, I'm a bit sceptical about the url decoding(like in decoding something you didn't encode yourself). I will check if a very complex url works as expected whenever I have a chance, and report back.  Thanks again
