### ISSUE TITLE
Data function not called for Route with param value

### ISSUE THREAD

**Issue by skclusive** [solidjs/solid-app-router#121]
Data function not called for different id value while staying in same route.

```jsx
<Routes>
     <Route
         path="page/:id"
         component={Page}
         data={({ params }) => ({ id: params.id })} /* data function not called for different id value while staying in same route */
      />
</Routes>
```
Workaround is using useParams and get data inside component. But fix for this is essential to fetch data as you render use cases.

[Reproducible Here](https://stackblitz.com/edit/vitejs-vite-pmnc3b)

**Comment by ryansolid** [comment]
This is intentional. Data functions are run once and params object is reactive. The expectation is that you use these to wrap reactive primitives like resources or signals. This way we can do more granular changes.

**Comment by skclusive** [comment]
oh. great. got it. the following works. i am good. closing the ticket.

```jsx
<Routes>
      <Route
          path="page/:id"
          component={Page}
         data={({ params }) => {
            const [data, setData] = createStore({ id: params.id });
            createEffect(
              on(
                () => params.id,
                () => {
                  setData('id', params.id);
                }
              )
            );
            return data;
          }}
        />
</Routes>
```
