### ISSUE TITLE
Handling 404

### ISSUE THREAD

**Issue by saiumesh535** [solidjs/solid-app-router#132]
### Describe the bug

Hello There. I'm not sure if this expected behavior from the router or If I'm missing something.

 I'm trying to navigate to the home page when no path is matched and below is my sample code. my understanding is whenever none of the routers matches it falls back onto the last route with path **"*"**. but since we have a star, even if I visit the `/login` page it redirects back to home. When I click on the login `Link` it actually redirects to login but not on reloads.
```jsx
import './App.css';
import { Routes, Route, Navigate, Router, Link } from 'solid-app-router';

const Login = () => {
  return <p>Login</p>;
};

const Signup = () => {
  return <p>signup</p>;
};

const Home = () => {
  return (
    <>
      <p>Home</p>
      <Link href="/login">Login</Link>
    </>
  );
};

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/login" element={<Login />} />
        <Route path="/signup" element={<Signup />} />
        <Route path="/" element={<Home />} />
        <Route path="*">
          <Navigate href={'/'} />
        </Route>
      </Routes>
    </Router>
  );
}

export default App;

```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-template-gbvscn?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Visit the link - https://stackblitz.com/edit/solidjs-template-gbvscn?file=src/App.tsx
2. click on the Login link, it redirects to the login 
3. Reload the page, it redirects to home rather than login 

### Expected behavior

Fallback onto the last route when none of the routers matches

### Platform

- OS: macOS
- Browser: Firefox
- Version: 0.4.1

**Comment by rturnq** [comment]
You just need to change the catch-all star route to put the Navigate component in the `element` prop instead of children. Route children are expected to be nested route definitions and are eagerly evaluated so the Navigate component would be causing a navigation on every page back to home on initial load.

```jsx
<Route path="*">
  <Navigate href={'/'} />
</Route>
```
becomes
```jsx
<Route path="*" element={<Navigate href={'/'} />} />
```

**Comment by saiumesh535** [comment]
Thanks, @rturnq it worked. do you mind if I add this example in this section? https://github.com/solidjs/solid-app-router#the-navigate-component

**Comment by DominicTobias** [comment]
> You just need to change the catch-all star route to put the Navigate component in the `element` prop instead of children. Route children are expected to be nested route definitions and are eagerly evaluated so the Navigate component would be causing a navigation on every page back to home on initial load.
> 
> ```js
> <Route path="*">
>   <Navigate href={'/'} />
> </Route>
> ```
> 
> becomes
> 
> ```js
> <Route path="*" element={<Navigate href={'/'} />} />
> ```

Thanks I got stuck on this too because the README gives an example of it as a child

**Comment by DominicTobias** [comment]
This isn't working for me. This redirects anything to `/en`:

```tsx
<Routes>
  <Route path="/:lang">
    <Route path="/manage" element={<Manage />} />
    <Route path="/" element={<Dashboard />} />
    <Route path="/*all" element={<NotFound />} />
  </Route>
  <Route path="/*">
    <Navigate href="/en" />
  </Route>
</Routes>
```

And this does nothing (the /*all path is ignored):

```tsx
<Routes>
  <Route path="/:lang">
    <Route path="/manage" element={<Manage />} />
    <Route path="/" element={<Dashboard />} />
    <Route path="/*all" element={<NotFound />} />
  </Route>
  <Route path="/*all" element={<Navigate href="/en" />} />
</Routes>
```
