### ISSUE TITLE
Discussions tab does not exist 

### ISSUE THREAD

**Issue by danielo515** [solidjs/solid-app-router#140]
### Describe the bug

The referenced discussions tab goes to a github 404 

### Your Example Website or App

Not needed

### Steps to Reproduce the Bug or Issue

Just click on the links in the issue template 

### Expected behavior

To have some discussion 😁

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
Oh I see we copied the Solid issue template. Hmm.. need to decide whether this repo should have its own discussions forum. It might be easier to keep things centralized. Not sure yet.

**Comment by danielo515** [comment]
I see you already enabled them. Thank you!
