### ISSUE TITLE
Changing URL directly got 404 not found

### ISSUE THREAD

**Issue by miello** [solidjs/solid-app-router#19]
Hello I have some problem when directly change the URL in URL bar or refresh page and it got "404 Not Found" but when I have changed URL by clicking on ```<Link>``` then it show the component normally

It's only affected to sub-route such as "/users", "/2", "/1" but the route "/" is perfectly fine.

Before refresh page
![image](https://user-images.githubusercontent.com/35169079/125909526-83d1fd3a-73ef-42f6-aefb-84303742764c.png)

After refresh page
![image](https://user-images.githubusercontent.com/35169079/125909628-99dcea63-afaa-4704-a01d-25e6e7e96cd9.png)

My project environment
- snowpack.js ^3.7.1
- solid.js ^1.0.0
- solid-app-router: ^0.0.51

*Edit
This is my snowpack config file
```/**
 * @type {import('snowpack').SnowpackConfig}
 */
const config = {
  mount: {
    public: "/",
    src: "/assets"
  },
  packageOptions: {
    installTypes: true,
    NODE_ENV: true
  },
  devOptions: {
    out: "dist",
    open: "none",
    bundle: true
  },
  buildOptions: {
    clean: true,
    out: "dist"
  },
  plugins: ["@snowpack/plugin-typescript", "@snowpack/plugin-babel", "@snowpack/plugin-postcss"],
  optimize: {
    bundle: true,
    minify: true,
    target: "es2020",
    treeshake: true,
    splitting: true
  }
};

module.exports = config;
```

**Comment by ryansolid** [comment]
Are you server rendering? Does snowpack know to always serve index.html? Getting 404 means it isn't even serving the page which means it isn't even getting to Solid's router in the browser. Maybe this is relevant: https://www.snowpack.dev/guides/routing

**Comment by miello** [comment]
Thanks for helping I think it works now, I need to add this into snowpack config 

```
routes: [
    {
      match: 'routes',
      src: '.*',
      dest: '/index.html',
    },
  ],
```
