### ISSUE TITLE
Allow sub path '*all' to match top level '*all' instead.

### ISSUE THREAD

**Issue by minht11** [solidjs/solid-app-router#22]
Common use case is to show completely empty not found page, if route doesn't match, without any specific sub path elements, currently this is not possible without redirects which change current path or some position absolute styling hacks.

In this example I wish to show top level Not Found page and not sub level one when no other routes match.
[Example](https://codesandbox.io/s/awesome-ramanujan-2p4rx?file=/index.js:0-1276)
```jsx
const User = () => (
  <div class="user-page">
    <div>User page</div>
    <Outlet />
  </div>
);
...
<Routes>
  <Route path="/" element={<div>Home</div>} />
  <Route path="/users" component={User}>
    <Route path="/" element={<div>User</div>} />
    <Route path="/sub" element={<div>UserSub</div>} />
    <Route
      path="/*all"
      element={
        <div>
          Foward this to top level "Not Found" page somehow
          while keeping current path.
        </div>
      }
    />
  </Route>
  <Route path="/*all" element={<div>Not Found</div>} />
</Routes>;
```

**Comment by minht11** [comment]
Instead of specifically matching '/*all' maybe better option would be to allow escaping nested routes after all other paths inside do not match and continue matching other top level ones. Something like `continue` keyword in javascript.
```jsx
<Route path="/users" component={User}>
    <Route path="/" element={<div>User</div>} />
    <ContinueEvaluatingOtherRoutes/>
</Route>
<Route path="/a" />
<Route path="/users/but-not-related" />
...
```

**Comment by ryansolid** [comment]
Yeah, falling back to parent * routes when there is no match makes more sense. I find I do mostly want to show nested not found pages and nested * routes is the only way you would do that.

**Comment by rturnq** [comment]
Another option is to add something to the path definition which would modify its meaning to only match when a child route matches.

```jsx
<Route path="/users!" component={User}> // <-- Only matches "/users", "users/foo" or "users/bar"
  <Route path="/" element={<div>User</div>} />
  <Route path="foo" element={<div>Foo</div>} />
  <Route path="bar" element={<div>Bar</div>} />
</Route>
```

This would have the same semantics as the "continue" proposal but would be different than the original concept as you lose the context when some parent catch-all route matches instead.

**Comment by minht11** [comment]
Adding option to the parent route itself definitely sounds like a better option, though I think explicit property, `matchOnlyNested, explicitPaths, matchOnlyDefined, noImplicitPaths, strict` or something similar, might be a bit clearer and also easier to teach:
```jsx
<Route path="/users" component={User} noImplicitMatching>
  <Route path="/" element={<div>User</div>} />
  <Route path="foo" element={<div>Foo</div>} />
  <Route path="bar" element={<div>Bar</div>} />
</Route>
```
Also it scopes functionality to only places where it does something: for example `!` would have no effect on `useMatch`, but would work on `Route` making path meaning different depending on the context.

That said depending in how many places you need to track if this option is enabled, `!` path might be easier to implement and it's meaning would be relatively similar to Typescript semantics, so both would work in my opinion.

**Comment by ryansolid** [comment]
I didn't put this in my response above but this is hardly a new pattern. You see this in Ember/Nuxt/RR6 etc.. I'm pretty sure they all work like this:
```js
<Routes>
  <Route path="/users" component={User}> // <-- Only matches "/users", "users/foo" or "users/bar"
    <Route path="/" element={<div>User</div>} />
    <Route path="foo" element={<div>Foo</div>} />
    <Route path="bar" element={<div>Bar</div>} />
  </Route>
  <Route path="/*all" element={<NotFound />} /> // Matches anything that doesn't match anything else
</Routes>
```
No need for explicit attributes or paths. It just is how it works.
If I want a wildcard under users I add it:
```js
<Routes>
  <Route path="/users" component={User}> 
    <Route path="/" element={<div>User</div>} />
    <Route path="foo" element={<div>Foo</div>} />
    <Route path="bar" element={<div>Bar</div>} />
    <Route path="/*all" element={<UsersNotFound />} /> // matches /users/*
  </Route>
  <Route path="/*all" element={<NotFound />} /> // Matches anything that doesn't match anything else
</Routes>
```
I think this is clear and doesn't add any additional concepts.

**Comment by ryansolid** [comment]
This one is merged now. It works as I describe in the previous post in 0.1.2.
