### ISSUE TITLE
Top level paths always matches even if nested paths were declared first

### ISSUE THREAD

**Issue by minht11** [solidjs/solid-app-router#23]
I am not sure if this is a bug or just me not understanding how routes priority works.
[Reproduction](https://codesandbox.io/s/intelligent-voice-5k87e?file=/index.js)
```jsx
<Route path="/" component={User}>
  <Route path="/users" element={<div>Should match this</div>} />
</Route>
<Route path="/users" element={<div>But matches this</div>} />
```
I discovered this while trying to use  `<Navigate>` and redirect  from `/|/users`  to `/users/default-route`

**Comment by rturnq** [comment]
Routes are matched breadth-first so at a given depth all siblings will be evaluated, a winner picked and it's children evaluated. Non-winning branches are not evaluated any further.

In this case, at the top level `/users` was prioritized over `/`. As you have it, those routes both match the same exact location ("/users") and neither will match further so any prioritization method will always leave one of them out. I'm not sure if it is your intent but if you want the top level `/users` route to match when the location is exactly "/users" and the other one to match "/users/some/thing/deeper" add a "/*" to the end of the path nested route's path:

```jsx
<Routes>
  <Route path="/" component={User}>
    <Route path="/users/*" element={<div>Should match this</div>} /> // <-- this will match '/users/foo/bar'
  </Route>
<Route path="/users" element={<div>But matches this</div>} /> // <-- this will only match '/users'
```

**Comment by minht11** [comment]
Thanks that makes sense.

**Comment by rturnq** [comment]
Just to follow-up on this, with PR #28 and v0.1.2, the matching strategy has been updated and makes declaration order the tie-breaker for equivalent paths. This changes what I had said previously and now your example works as you expected it.
