### ISSUE TITLE
The active class triggers for `NavLink`s using the `/` path, regardless of what path you visit.

### ISSUE THREAD

**Issue by CitrusFruits** [solidjs/solid-app-router#27]
**Summary**: The active class triggers for `NavLink`s using the `/` path, regardless of what path you visit.

**Steps to reproduce**:
1. Run the following code
2. Navigate to the "list" page

**Expected result**: Only the list `NavLink` has an `active` class
**Actual result**: Boththe `NavLink`s have an `active` class

``` javascript
import { MountableElement, render } from "solid-js/web";
import { Router, useRoutes, NavLink } from "solid-app-router";

const routes = [
	{
		path: "/",
		component: () => <div>Home</div>
	},
	{
		path: "/list",
		component: () => <div>List</div>,
	},
];

function App() {
	const Routes = useRoutes(routes);
	return (
		<>
			<NavLink href="/">
				Home
			</NavLink>
			<NavLink href="/list">
				List
			</NavLink>
			<Routes />
		</>
	);
}

render(
	() => (
		<Router>
			<App />
		</Router>
	),
	document.getElementById("app") as MountableElement
);
```

**Commentary**
I get the logic behind this, in that if you are visiting `product/<some id here>` you might want to match against a `/product` `NavLink`. But I think there still should be a way to get an active class on your root directory without it always having to be active.

Also, thanks for all the hard work you guys have done on this router, and solidjs in general!

**Comment by CitrusFruits** [comment]
I just found the `end` property, which solves for this use case.

``` jsx
<NavLink end={true} href="/">
	Home
</NavLink>
```

**Comment by ryansolid** [comment]
I need to work on the docs a bit I see. I am also interested in what React Router does here. I guess I care most about React Router 6 which I'm not sure people are really using yet.

**Comment by rturnq** [comment]
They use `end` as well.

**Comment by ryansolid** [comment]
Ok I've made mention in the docs.

**Comment by dougsmith1000** [comment]
@ryansolid I didn't see this in the docs. Should I add it? Or am I just missing it.
