### ISSUE TITLE
How to get the source route?

### ISSUE THREAD

**Issue by 6643** [solidjs/solid-app-router#29]

**Comment by rturnq** [comment]
Can you please elaborate on your question? It isn't clear (to me at least) what you are referring to when you say "source route".

**Comment by 6643** [comment]
a page jumps to b page

In page b, how to get which page is jumping over

route.from?

**Comment by SanichKotikov** [comment]
Hi. From v0.1.13 you can use something like that:

```ts
const navigate = useNavigate();
const location = useLocation();

navigate('/some/path', { state: { prev: location.pathname } })
```

```ts
const location = useLocation<{ prev: string }>();
navigate(location.state?.prev || '/');
```

To avoid copy/paste you also can wrap this code into your own useNavigate and useLocation hooks.

**Comment by ryansolid** [comment]
I think this is a reasonable answer, that or the issue is stale. Closing it.
