### ISSUE TITLE
SSR with router

### ISSUE THREAD

**Issue by galchenkov** [solidjs/solid-app-router#32]
Hi all, I apologize in advance for the translation. 

I am trying to start writing in this wonderful framework. I have set up a project build for server side rendering. Everything works fine for me. But I decided to use this router to move forward. Client-side works fine, but after connecting the library, server-side stopped building.

ERROR in ./node_modules/solid-app-router/dist/index.js 503:15-23
export 'template' (imported as 'template') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, HydrationScript, Index, Match, NoHydration, Portal, Show, Suspense, SuspenseList, Switch, createComponent, escape, generateHydrationScript, getHydrationKey, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrBoolean, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle)
 @ ./src/shared/App.tsx 14:0-42 79:27-33
 @ ./src/server/index.tsx 10:0-35 34:39-42

ERROR in ./node_modules/solid-app-router/dist/index.js 652:4-10
export 'insert' (imported as 'insert') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, HydrationScript, Index, Match, NoHydration, Portal, Show, Suspense, SuspenseList, Switch, createComponent, escape, generateHydrationScript, getHydrationKey, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrBoolean, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle)
 @ ./src/shared/App.tsx 14:0-42 79:27-33
 @ ./src/server/index.tsx 10:0-35 34:39-42

ERROR in ./node_modules/solid-app-router/dist/index.js 654:4-10
export 'effect' (imported as 'effect') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, HydrationScript, Index, Match, NoHydration, Portal, Show, Suspense, SuspenseList, Switch, createComponent, escape, generateHydrationScript, getHydrationKey, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrBoolean, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle)
 @ ./src/shared/App.tsx 14:0-42 79:27-33
 @ ./src/server/index.tsx 10:0-35 34:39-42

ERROR in ./node_modules/solid-app-router/dist/index.js 654:17-29
export 'setAttribute' (imported as 'setAttribute') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, HydrationScript, Index, Match, NoHydration, Portal, Show, Suspense, SuspenseList, Switch, createComponent, escape, generateHydrationScript, getHydrationKey, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrBoolean, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle)
 @ ./src/shared/App.tsx 14:0-42 79:27-33
 @ ./src/server/index.tsx 10:0-35 34:39-42

ERROR in ./node_modules/solid-app-router/dist/index.js 720:0-14
export 'delegateEvents' (imported as 'delegateEvents') was not found in 'solid-js/web' (possible exports: Assets, Dynamic, ErrorBoundary, For, HydrationScript, Index, Match, NoHydration, Portal, Show, Suspense, SuspenseList, Switch, createComponent, escape, generateHydrationScript, getHydrationKey, isServer, mergeProps, pipeToNodeWritable, pipeToWritable, renderToString, renderToStringAsync, resolveSSRNode, spread, ssr, ssrBoolean, ssrClassList, ssrHydrationKey, ssrSpread, ssrStyle)
 @ ./src/shared/App.tsx 14:0-42 79:27-33
 @ ./src/server/index.tsx 10:0-35 34:39-42

**Comment by zhengjiaqi** [comment]
I met the same problem, how did you solve it？
