### ISSUE TITLE
Using a <Link> component to navigate to the current route does not update data

### ISSUE THREAD

**Issue by CitrusFruits** [solidjs/solid-app-router#34]
It seems routing to the current page, but using a different pattern than the one you are currently on, does not update the data associated with that route. An example of when this might be done is on a product page, linking to another related product.

**Steps to reproduce:**
1. Run the given code on a server
2. Visit https://127.0.0.1/foo/1
3. Click on "Go to page 2"

**Expected result:** The title reads "You are on page 2"
**Actual result:** The title reads "You are on page 1", even though the URLhas updated

``` jsx
import { createSignal, Accessor } from 'solid-js';
import { MountableElement, render } from 'solid-js/web';
import { Router, Routes, Route, Link, useData } from 'solid-app-router';
import { Params } from 'solid-app-router';

function FooData({ params }: { params: Params}): Accessor<number| undefined> {
	return createSignal(parseInt(params.id))[0];
}

function Foo() {
	const routingData = useData() as Accessor<number| undefined>;

	return <>
		<h1>You are on page {routingData()}</h1>
		<Link href={`/foo/1`}>Go to page 1</Link>
		<br/>
		<Link href={`/foo/2`}>Go to page 2</Link>
	</>;
}

render(
	() => (
		<Router>
			<Routes>
				<Route path="/foo/:id" element={<Foo />} data={FooData} />
			</Routes>
		</Router>
	),
	document.getElementById('app') as MountableElement
);
```

(Screenshot of step 2)
![image](https://user-images.githubusercontent.com/2839268/128790247-603eed61-89b0-477f-aaec-bf8e1ff537e9.png)
(Screenshot of step 3)
![image](https://user-images.githubusercontent.com/2839268/128790257-e3807415-abc0-429f-ba7a-d4b9ae275964.png)

**Comment by rturnq** [comment]
I think this is a case of needing more documentation on the matter. As you have found, the route data functions only execute initially when the route is matched and won't run again until that route is un-matched and then matched again. This aligns with Solid's concept of components which similarly only run initially when created.

In order to handle the scenario you have, you'll want to leverage the reactive nature of the `params` or `location` properties passed into the function and derive your result. So in this case, instead of creating a signal you could use a memo or even a simple function. If you have async data needs, use a resource with the first argument based on the reactive values.

```ts
function FooData({ params }: { params: Params}): Accessor<number> {
  return () => parseInt(params.id)
}
```
```ts
function FooData({ params }: { params: Params}): Accessor<number> {
  return createMemo(() => parseInt(params.id))
}
```
```ts
function FooData({ params }: { params: Params}): { id: number } {
  return {
    get id() {
      return parseInt(params.id)
    }
  }
}
```
```ts
function FooData({ params }: { params: Params}) {
  const [resource] = createResource(() => parseInt(params.id), (id) => /* fetch some data */);
  return resource;
}
```

**Comment by CitrusFruits** [comment]
_Got it_. Ok yeah, looks like I'm still getting more familiar with the fundamentals of SolidJS. Brushing up on the documentation, this line now makes more sense:

>Remember to access signals under a tracking scope if you wish them to react to updates. Tracking scopes are functions that are passed to computations like createEffect or JSX expressions.

If someone else stumbles upon this, I was using `createResource` in my actual app, but I was not creating a tracking scope for my parameters. So I was doing this:

``` javascript
function FooData({ params }: { params: Params}) {
  const [resource] = createResource(parseInt(params.id), (id) => /* fetch some data */);
  return resource;
}
```

instead of this

``` javascript
function FooData({ params }: { params: Params}) {
  const [resource] = createResource(() => parseInt(params.id), (id) => /* fetch some data */);
  return resource;
}
```

Thanks @rturnq!
