### ISSUE TITLE
Default value of `href`

### ISSUE THREAD

**Issue by pheianox** [solidjs/solid-app-router#35]
Could you add an option for empty links. Links that could be used as buttons, for example. 
Then usually don't need `href`. But a link must have `href`, so there's a trick with `javascript:void(0)`.

Input
```jsx
<Link>To the moon</Link>
```
Output
```html
<a href="javascript:void(0)">To the moon</a>
```

The idea is to set `href` to `javascript:void(0)` as a default value.

**Comment by bramaudi** [comment]
i wonder what the use case of this? if you want to bind with event i usually use button not a link.

**Comment by CitrusFruits** [comment]
I'm pretty sure `<Link>` is just a wrapper around the `<a>` anyways, so if you wanted this specific functionality, it might just be better to do it yourself using an `<a>` JSX Element.

**Comment by ryansolid** [comment]
Yeah I suspect that since this is just a conceptual passthrough we aren't going to implement some different behavior here.
