### ISSUE TITLE
Using `useNavigate()` threw an error

### ISSUE THREAD

**Issue by cunc** [solidjs/solid-app-router#36]
When call the `useNavigate` function, `useRouter()` cannot find a router context. 

`Uncaught Error: Make sure your app is wrapped in a <Router />` arises, but the app is certainly wrapped in a Router component.

Here is some of the code:
 ```js
// index.tsx
import { render } from 'solid-js/web'
import { Router, useRoutes } from 'solid-app-router'
import { Component, lazy } from 'solid-js'

const routes = [
  {
    path: '/',
    component: lazy(() => import('./pages/Home')),
    children: [
      {
        path: '/',
        component: lazy(() => import('./pages/scripts/ScriptList')),
      },
      {
        path: '/script/add',
        component: lazy(() => import('./pages/scripts/ScriptAdd')),
      },
    ],
  },
]

const App: Component = () => {
  const Routes = useRoutes(routes)
  return <Routes />
}

render(
  () => (
    <Router>
      <App />
    </Router>
  ),
  document.getElementById('root')
)

// other.tsx
import { useNavigate } from 'solid-app-router'

const fn = () => {
  const navigate = useNavigate()
  navigate('/script/add')
}
```

Is anything wrong in this?

**Comment by ryansolid** [comment]
Context only works under component render/primitive(hook) execution. If you call use from like an event handler context it won't be there. I suspect that is what is happening here.

**Comment by cunc** [comment]
@ryansolid Thank you so much. It works well after taking the function out of the event handler scope.

**Comment by jmagaram** [comment]
I am having this problem and don't understand the solution. In my component there is a button, and when you click on it, I need to navigate to a specific page after taking various actions. Those actions happen inside the click handler callback of the button. How can I move the navigate call outside of the click handler?

**Comment by Brendan-csel** [comment]
Try grabbing a reference to `navigate` at the top of your function, then use it in the event handler...

```js
function Counter() {
  const navigate = useNavigate();

  return (
    <button 
      onClick={() => {
        // do other stuff
        navigate("somewhere");
      }}
    >
      Click Me
    </button>
  );
}
```
