### ISSUE TITLE
Expose RouteProps to public

### ISSUE THREAD

**Issue by kevineaton603** [solidjs/solid-app-router#37]
Allows `Route` component to be extended or encapsulated. i.e. if I want an authenticated route, a good pattern might be...

```tsx
type AuthenticatedRouteProp = RouteProp & { isAuthed: boolean };
const AuthenticatedRoute: Component<RouteProp> = (props) => {
  return (
    { props.isAuthed ? <Route {...props} /> : <Navigate href={'/login'} /> }
  );
} ;
```

which means that `RouteProp` needs to be exposed

**Comment by rturnq** [comment]
I don't think this will quite work. The `Route` component actually just returns the props object which is then consumed by the `Routes` component. It isn't really a normal component, but more of a way to inject the route configuration leveraging the tree structure JSX children give us. All of the route components are evaluated before `Routes` renders so any route which returns a `Navigate` I would think would cause a navigation to occur immediately, regardless of if that route matches.

Route rendering on match occurs in the `element` or `component` defined on the `Route`, so it would be more appropriate to put the navigation in there. I think the easiest would be to just wrap another route around those you want authorized but you could also possibly encapsulate that as well. Something like (untested):

```jsx
const AuthenticatedRoute = (props: AuthenticatedRouteProps) => {
  const [, rest] = splitProps(props, ["isAuthed", "path"]);
  return (
    <Route
      path={props.path}
      component={() => props.isAuthed ? <Outlet /> : <Navigate href="/login" />}
    >
      <Route {...rest as RouteProps} path="" />
    </Route>
  );
};
```

This would probably need to have some extra logic to handle paths which end in a `*`.

**Comment by kevineaton603** [comment]
New to solid.js and its ecosystem so I don't know how to leverage all the API's quite yet. But this definitely makes sense! Thank you for your help!
