### ISSUE TITLE
support conditional Route

### ISSUE THREAD

**Issue by francois-pasquier** [solidjs/solid-app-router#40]
I'd like to render one Route or another depending on the data from a store.

Is it supported somehow?

**Comment by rturnq** [comment]
Are you looking to just swap out the rendered component and keep the route's path or something else? For example would you keep the route's path and things like data the data fetcher? Maybe you can elaborate a little more on your use-case so we can determine a good solution.

**Comment by francois-pasquier** [comment]
I'd like to restrict access to some routes depending on if the user is logged in or not.

Like let's say the  '/profile'  route would be accessible only for a logged in user.

**Comment by rturnq** [comment]
I see two ways this could be approached. The first option and what I would recommend, is pushing the condition into a route component and leverage the router's compositional nature. One can group protected routes under another route which provides the auth check within it's component. Here is an example of what I'm suggesting: https://codesandbox.io/s/solid-app-router-protected-routes-qt5mv

The second approach is putting the condition within the route definitions themselves. This is not actually supported by the router today but is achievable with a couple of minor modifications. Here is an example of how that might look: https://codesandbox.io/s/solid-app-router-conditional-routes-c2hq (again this requires changes to the router). This option has a couple of downsides in my view. First it makes the static form of the route definitions a little trickier as the state/signal needs to be in context for it to be accessible. Second and more important, making the route definitions conditional deprives the router of knowledge of possible routes which limits its ability to do things like preloading/prefetching and run data functions for the branch of routes hidden by the condition.

Implementing both of these examples has highlighted an issue for me around how routes are identified as changed between navigations which we'll need to be addressed. Also, I see little downside to supporting conditional definitions if that helps solve someone's use-case. I'll let @ryansolid chime in with any thoughts he has on the matter.

**Comment by francois-pasquier** [comment]
Thank you, the first option should do the trick, cheers!

**Comment by ryansolid** [comment]
This does need some more thought in general though. I think it is reasonable to expect the 2nd option to work and we need to work through what that means.
