### ISSUE TITLE
Improve documentation for useLocation

### ISSUE THREAD

**Issue by mneumann** [solidjs/solid-app-router#50]
The `parseQuery` in the example for `useLocation` is a bit misleading IMHO. Mention that `location.query` returns a `Proxy` that can be used to access the query parameters, e.g.

```javascript
const location = useLocation();

return <p>{location.query.code}</p>;
```

Also mention whether query parameters are downcased or not, so whether `?confirmationCode=123` has to be accessed as `location.query.confirmationcode` or `location.query.confirmationCode`.

**Comment by ryansolid** [comment]
We've add a new `useSearchParams` and added documentation for it. Hopefully this fulfills the need much better and the documentation is more detailed.
