### ISSUE TITLE
Go to previous route

### ISSUE THREAD

**Issue by SanichKotikov** [solidjs/solid-app-router#51]
Hi.

For example, as a user I can navigate to some edit page from different routes, and after changes is applied, I need to navigate back to previous route. Is there any way to do this?

If I remember right, in react-router there was a state that can be anything (for example `state: { prev: location.pathname }`). But state here is just a string or null. And looks like it doesn't work (or I don't understand something). `navigate('/users/edit', { state: location.pathname })` after this, I've still got null state on edit page.

**Comment by rturnq** [comment]
Thank you again for the PR, is had been released in v0.1.13.
