### ISSUE TITLE
default page when parent is click

### ISSUE THREAD

**Issue by code404sg** [solidjs/solid-app-router#55]
Hi is this possible?
From 
![image](https://user-images.githubusercontent.com/60589025/143670560-3c4644f9-1cc4-45b4-9c41-a43f74f115e0.png)
To
![image](https://user-images.githubusercontent.com/60589025/143670578-ac4fd164-062e-4033-9816-d8e5109fee02.png)

I want to achieve is when i click the parent link. then the first(or any) child should be the default page to show.

Thanks for help.

**Comment by rturnq** [comment]
I'm not entirely sure what you are looking for but it sounds like you might want something like this: https://codesandbox.io/s/solid-app-router-nested-routes-c72ps

**Comment by code404sg** [comment]
thanks. it works.
