### ISSUE TITLE
route no working in production build

### ISSUE THREAD

**Issue by code404sg** [solidjs/solid-app-router#58]
Hi, 
When im in development, button is navigating to another url.
but when i run <code>npm run build</code>
and i do <code>npm run serve</code>
and i click the button to navigate its not working only the url is change.

TIA

**Comment by rturnq** [comment]
Do you have an example which can reproduce the issue? If not [here is an example](https://github.com/rturnq/solid-app-router-issue-58) I quickly bootstrapped using Solid's [getting started guide](https://www.solidjs.com/guide). Navigation seems to work as expected in dev and production builds using both the Link components and imperative navigation (eg. `useNavigate`) API. Maybe your app is doing something more complex? Either way, we'll need to see some more information to proceed.

**Comment by code404sg** [comment]
@rturnq thanks a lot.
```
render(() => 
    <SocketContext>
        <Router>
        <StoreonProvider store={store}>
            <App />
        </StoreonProvider>
        </Router>
    </SocketContext>
, document.getElementById("root"));
```
i have this inside index.jsx
when i put socketcontext inside router its working.
but when i navigate my websocket is keep on reconnecting even though its connected.
here is my SocketContext
```
import { io } from 'socket.io-client';
import { createContext, useContext } from "solid-js";

const SocketContext = createContext();

const SocketProvider = (props) => {
  const socket = io(`http://localhost:3002`, { 
    reconnectionDelayMax: 5000,
    reconnectionAttempts: 5,
    timeout: 5000,
    rememberTransport: false, 
    transports: ['websocket']
  });

  return (
    <SocketContext.Provider value={socket}>
      {props.children}
    </SocketContext.Provider>
  );
}

export function useWebSocket() { return useContext(SocketContext); }
export default SocketProvider;
```
