### ISSUE TITLE
Routing doesn't work in production when changed the url

### ISSUE THREAD

**Issue by TheBoringDude** [solidjs/solid-app-router#63]
I tried to fork this repo from [https://github.com/rturnq/solid-app-router-issue-58](https://github.com/rturnq/solid-app-router-issue-58) and deployed it to test the routing.

It works when you click the links from the main index page but if you go to a specific route by changing the url it doesn't work. Sample going to this link [https://solid-app-router-issue-58.vercel.app/page1](https://solid-app-router-issue-58.vercel.app/page1)

Demo: [https://solid-app-router-issue-58.vercel.app](https://solid-app-router-issue-58.vercel.app)

**Comment by TheBoringDude** [comment]
**UPDATE:**

I have found a solution for Vercel. I needed to add a `vercel.json` config file to rewrite route configuration.

```json
{
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}
```

**Comment by bramdoppen** [comment]
> **UPDATE:**
> 
> I have found a solution for Vercel. I needed to add a `vercel.json` config file to rewrite route configuration.
> 
> ```json
> {
>   "rewrites": [
>     {
>       "source": "/(.*)",
>       "destination": "/index.html"
>     }
>   ]
> }
> ```

Thanks! This should be somewhere underneath a deployment section in the documentation of Solid Router.
