### ISSUE TITLE
Route to path ="/" is not working in electron.js

### ISSUE THREAD

**Issue by DhansAL** [solidjs/solid-app-router#65]
## td,dr

need `Hashrouter` equivalent for solid.

I was trying the routing in a basic electron app and got stuck with this.

The path="/" works fine in browsers but I cannot GET that page in my electron window.

#### STEPS TO REPRODUCE

`app.tsx`

```typescript

import { Link ,Route, Routes } from "solid-app-router";

export const App = () => {
  const Nav = () => {
    return (
      <>
      <div style={{display:"flex"}}>
      <Link style={{"margin-right":"10px"}} href="/">homepage</Link>
      <Link style={{"margin-right":"10px"}} href="/newcomponent">new component</Link>
      </div> 
      </>
    );
  };
  const Homepage = () => {
    return (
      <>
        <Nav />
        <div>homepage component.</div>
      </>
    );
  };
  const Component1 = () => {
    return (
      <>
        <Nav />
        <div>new component.</div>
      </>
    );
  };
  return (
    <>
      {/* <Nav />  */} 
      <Routes>
        <Route path="/" element={<Homepage />} />
        <Route path="/newcomponent" element={<Component1 />} />
      </Routes>
    </>
  );
};

```

`index.tsx` 

```typescript
import { render } from "solid-js/web";
import { Router } from "solid-app-router";
import { App } from "./app.main";

render(
  () => (
    <Router>
      <App />
    </Router>
  ),
  document.getElementById("app")
);
`
```

#### EXPECTED OUTPUT

This code was supposed to show ` Homepage `  component on loading the window.

#### OUTPUT -

Both components were not loaded. I have to make the `Nav` component load on every page to route between pages.
The default path="/" is not getting loaded.

#### TECHSTACK

- solid.js ^1.2.6
- solid-app-router ^0.1.14
-  electron ^16.0.5

##### for creating a local solid-electron instance 

use - https://github.com/DhansAL/solidjs-electronForge-TS-template

**Comment by DhansAL** [comment]
> I was trying the routing in a basic electron app and got stuck with this.
> 
> The path="/" works fine in browsers but I cannot GET that page in my electron window.
> 
> #### STEPS TO REPRODUCE
> `app.tsx`
> 
> ```ts
> import { Link ,Route, Routes } from "solid-app-router";
> 
> export const App = () => {
>   const Nav = () => {
>     return (
>       <>
>       <div style={{display:"flex"}}>
>       <Link style={{"margin-right":"10px"}} href="/">homepage</Link>
>       <Link style={{"margin-right":"10px"}} href="/newcomponent">new component</Link>
>       </div> 
>       </>
>     );
>   };
>   const Homepage = () => {
>     return (
>       <>
>         <Nav />
>         <div>homepage component.</div>
>       </>
>     );
>   };
>   const Component1 = () => {
>     return (
>       <>
>         <Nav />
>         <div>new component.</div>
>       </>
>     );
>   };
>   return (
>     <>
>       {/* <Nav />  */} 
>       <Routes>
>         <Route path="/" element={<Homepage />} />
>         <Route path="/newcomponent" element={<Component1 />} />
>       </Routes>
>     </>
>   );
> };
> ```
> 
> `index.tsx`
> 
> ```ts
> import { render } from "solid-js/web";
> import { Router } from "solid-app-router";
> import { App } from "./app.main";
> 
> render(
>   () => (
>     <Router>
>       <App />
>     </Router>
>   ),
>   document.getElementById("app")
> );
> `
> ```
> 
> #### EXPECTED OUTPUT
> This code was supposed to show `Homepage` component on loading the window.
> 
> #### OUTPUT -
> Both components were not loaded. I have to make the `Nav` component load on every page to route between pages. The default path="/" is not getting loaded.
> 
> ### THIS CODE WORKS AS EXPECTED IN BROWSERS.
> #### TECHSTACK
> * solid.js ^1.2.6
> * solid-app-router ^0.1.14
> * electron ^16.0.5
> 
> ##### for creating a local solid-electron instance
> use - https://github.com/DhansAL/solidjs-electronForge-TS-template

**Comment by Brendan-csel** [comment]
I know nothing about Electron - but your issue mentions needing hash routing for solid-app-router.  You can do that...
```
  import {hashIntegration, Router} from "solid-app-router";

  <Router source={hashIntegration()}>
  ...
  </Router>
```

**Comment by DhansAL** [comment]
this works fine, thanks a lot ^_^
