### ISSUE TITLE
Serve + Nested Routing results in Error

### ISSUE THREAD

**Issue by cawfeecoder** [solidjs/solid-app-router#66]
I'm currently using serve with the following config to redirect all routes back to index.html:
```
{
  "rewrites": [
    { "source": "/**", "destination": "/index.html" },
    { "source": "/**/**", "destination": "/index.html" }
  ]
}

```

My Routes are defined as follows in Solid:
```
const AppRoutes = () => {
  return (
    <Routes>
      <Route
        path="/"
        element={
          <div>
            <Link href={'/app/2'}>Link</Link>
          </div>
        }
      />
      <Route path={'/app'}>
      <Route path={'/'} element={<p>Hi</p>}></Route>
        <Route path={'/*all'} element={<p>Hello</p>}></Route>
      </Route>
    </Routes>
  );
};
```

Going directly in the browser to localhost:3000/app results in the correct <p>Hi</p> being displayed. Clicking the link if I go to localhost:3000 correctly displays <p>Hello<p>.

**However, if I decide to hit localhost:3000/app/2 in my address bar, I get the following errors**:
```
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (runtime.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (solid-js.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (regexparam.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (rturnq.js:1)
[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (main.js:1)
[Error] Did not parse stylesheet at 'http://localhost:3000/app/main.css' because non CSS MIME types are not allowed in strict mode.
```
I'm using the latest solid/solid-router and webpack

Any chance there's a known solution to this and I'm just being dumb?

**Comment by ryansolid** [comment]
It looks like your paths for your assets in your `index.html` are relative rather than absolute. So when you refreshing it can't find things like `main.css` in the right place. So when you are at `/` then it's `/main.css` which exists.. but when you are at `/app` it tries `/app/main.css` which doesn't.

**Comment by ryansolid** [comment]
Closing as stale.
