### ISSUE TITLE
Symbolic useData

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid-app-router#71]
As [discussed in Discord](https://discord.com/channels/722131463138705510/780502110772658196/929177157652082801), the current numeric input to `useData` is brittle (even with the negative-number extension of #69). Using a component at different depths of the hierarchy makes it difficult to find the right ancestor data.

The general agreement from the thread was to introduce a context-like API. I believe the plan is to pass in the same function that was given as a `data` attribute to the `Route`.  For example, `<Route data={UserData}>` woudl get accessed like so:
```js
const data = useData(UserData);
```
Type-wise, this could work as follows:
```js
function useData<T>(dataFunc: () => T): T | undefined;
  // returns undefined if no ancestor route uses this dataFunc
```
There was also discussion about `useDataLoader` but that seemed more specific to `Resource`s (maybe a Solid Start thing?).

A related question is whether this should replace the existing numeric model (breaking change), or augment it as a second option (more code). I think at least we should preserve the common case, where `useData()` returns the current route's data, though this version will be better for typing even in that case.

**Comment by ryansolid** [comment]
Fixed with new solution in 0.3.x.
