### ISSUE TITLE
Upgraded from 0.1.9 to 0.2.1 and URL no longer changes when switching routes

### ISSUE THREAD

**Issue by kee-oth** [solidjs/solid-app-router#77]
I upgraded from 0.1.9 to 0.2.1 and the URL no longer changes when switching routes even though the route does change.

I downgraded and everything worked correctly so it seems to be caused by some change in between those versions. The page history just doesn't seem to be getting updated. I can open a new tab, click around to different pages, and then click the browser "Back" button and I get taken back to the new tab page (none of the app routes were added to history).

Did something change that requires modification to how we need to implement solid-app-router?

I'm getting this error when changing paths as well:

```
Uncaught TypeError: start(...) is undefined
    navigateFromRoute routing.js:230
    untrack dev.js:399
    navigateFromRoute routing.js:194
    navigatorFactory routing.js:248
    handleClick components.jsx:87
    eventHandler dev.js:333
    delegateEvents dev.js:119
    <anonymous> components.jsx:240
routing.js:230:26
    navigateFromRoute routing.js:230
    untrack dev.js:399
    navigateFromRoute routing.js:194
    navigatorFactory routing.js:248
    handleClick components.jsx:87
    eventHandler dev.js:333
    (Async: EventListener.handleEvent)
    delegateEvents dev.js:119
    <anonymous> components.jsx:240
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    evaluation self-hosted:2349
```

Thanks!

**Comment by ryansolid** [comment]
Try updating Solid to 1.3.0 or later. I am pretty sure the mismatch and the reason we went to 0.2.x was because we need to make changes for Solid 1.3 or later.

**Comment by kee-oth** [comment]
That worked, thanks!
