### ISSUE TITLE
NavLink  do not apply active class in nested routing

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-app-router#78]
I have nested routes like:

```jsx
 <Route path="/friends" element={<FriendsLayout />}>
        <Route path="/" element={<AllFriends />} />
        <Route path="/suggestions" element={<FriendsSuggestions />} />
        <Route
          path="/requests-received"
          element={<FriendsRequestsReceived />}
        />
        <Route path="/requests-sent" element={<FriendsRequestsSent />} />
 </Route>
```

When i switch to /friends active class applied by NavLink inside navbar  but when i switch to /friends/suggestions active class do not applied by NavLink on /friends inside navbar.

**Comment by harshmangalam** [comment]
Thanks @rturnq i got it. But is any way to get active property in className as a function parameter when navlink will active instead of applying active class direactly so that it can be easily styled inside jsx  like:

`className = {(active) => // apply  active design}`

or in classList like:
`classList={(active) => ({"bg-blue-500":active})}`

**Comment by rturnq** [comment]
You can specify the class you want to apply when it is active like
`activeClass="bg-blue-500"`

It isn't exactly the same as what you are suggesting as there isn't a converse non-active class but it might work for your case.

**Comment by harshmangalam** [comment]
Thanks @rturnq
