### ISSUE TITLE
How to use from solid-ssr

### ISSUE THREAD

**Issue by radensoft** [solidjs/solid-app-router#79]
Solid-app-router not working from solid-ssr, please help me

[!] Error: Could not resolve './components' from node_modules\solid-app-router\dist\index.jsx
Error: Could not resolve './components' from node_modules\solid-app-router\dist\index.jsx
    at error (C:\Users\info\Downloads\solid-ssr\node_modules\rollup\dist\shared\rollup.js:160:30)
    at ModuleLoader.handleResolveId (C:\Users\info\Downloads\solid-ssr\node_modules\rollup\dist\shared\rollup.js:22414:24)

**Comment by ryansolid** [comment]
What build setup are you using? Here is an example using the router with basically the same example I have in the solid-ssr repo. It is a bit out of date but might shed some light? https://github.com/ryansolid/solid-ssr-workbench

It looks like there is some issue going on with module resolution. Maybe a missing plugin like @rollup/node-resolve or some setting like that.

**Comment by radensoft** [comment]
termakasih atas balasan nya, tolong buat project sample SSR yang support extention .jsx, saya ingin project yang sudah ada bisa berjalan di SSR. terimakasih banyak
