### ISSUE TITLE
After upgrading to 0.1.14 version, url is no longer being updated on route change

### ISSUE THREAD

**Issue by illiaChaban** [solidjs/solid-app-router#81]
After upgrading solid-app-router from "0.1.7" to "0.1.14", the url is no longer updated on path change.
I'm using "solid-js": "^1.3.5"

**Comment by rturnq** [comment]
There was a small breaking change in Solid 1.3 which affected the router. The 0.2.x version of the router account for this. I will add something to the readme to indicate the version change

**Comment by illiaChaban** [comment]
thank you. I didn't know there was 0.2 version when trying to upgrade
