### ISSUE TITLE
createResource() unusual behaviour with useParams()

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-app-router#85]
```
const { userId } = useParams();
const [resource, { refetch }] = createResource(userId, fetchUserDetails);

return (
    <div>.......user details section.......</div>
    <div>
        <Outlet />
     </div>
)
```

when userId change createResource not call fetchuserDetails . But page like "post" , etc render inside Outlet are calling their fetcher function when userId change.

/profile -------> does not call fetcher on userId change
/profile/posts --------> calling fetcher fn on userId changes

when i try to debug userId using createEffect i found that it do not log the userId when userId is changing.

**Comment by ryansolid** [comment]
It's a proxy object to track reactivity similar to props. It should work if you don't destructure. Also to track the first argument to create resource is expecting an accessor function for it to track.

This should work:
```js
const params = useParams();
const [resource, { refetch }] = createResource(() => params.userId, fetchUserDetails);

return (
    <div>.......user details section.......</div>
    <div>
        <Outlet />
     </div>
)
```

**Comment by harshmangalam** [comment]
> It's a proxy object to track reactivity similar to props. It should work if you don't destructure. Also to track the first argument to create resource is expecting an accessor function for it to track.
> 
> This should work:
> 
> ```js
> const params = useParams();
> const [resource, { refetch }] = createResource(() => params.userId, fetchUserDetails);
> 
> return (
>     <div>.......user details section.......</div>
>     <div>
>         <Outlet />
>      </div>
> )
> ```

Still not work.

**Comment by harshmangalam** [comment]
> > It's a proxy object to track reactivity similar to props. It should work if you don't destructure. Also to track the first argument to create resource is expecting an accessor function for it to track.
> > This should work:
> > ```js
> > const params = useParams();
> > const [resource, { refetch }] = createResource(() => params.userId, fetchUserDetails);
> > 
> > return (
> >     <div>.......user details section.......</div>
> >     <div>
> >         <Outlet />
> >      </div>
> > )
> > ```
> 
> Still not work.

Other section is working even i destructure the userId .

**Comment by ryansolid** [comment]
It might be helpful to share a reproduction. From the provided code and description that is all the help I can give. Reactivity works the way I described so if you are seeing some other behavior something else is going on beyond what you've shared.

**Comment by harshmangalam** [comment]
<Route path="/:userId" element={<ProfileLayout />}>
          <Route path="" element={<ProfilePosts />} />
</Route>

---------------------------<ProfileLayout/>----------------------------

const params = useParams();
 const [resource, { refetch }] = createResource(
    params.userId,
    fetchUserDetails
  );


return (
....
..............profile details using resource()..................
 <Outlet />
....
)

when userId is changing then <ProfilePosts/> component are able to get reactive userId from useParams but <ProfileLayout/> component are not. When i try to debug useParams() in createEffect i got nothing.

**Comment by rturnq** [comment]
In that last code snippet, the first parameter of `createResource` needs to be a function in order for the resource to reactively track  values and call `fetchUserDetails` again. As you have it, it will work initially when the component is first rendered and use whatever value is in the `userId` parameter but keep in mind the component will not re-render between navigating from say `/123` to `/456`, only `params.userId` will change. This is also why destructuring is problematic - since it takes the current value and creates a local variable which will never change.

Maybe this example will help: https://codesandbox.io/s/solid-app-router-template-forked-jcpmu2

**Comment by harshmangalam** [comment]
Thanks @rturnq. Now working
