### ISSUE TITLE
Hash integration not working with 0.3.0

### ISSUE THREAD

**Issue by fireph** [solidjs/solid-app-router#86]
Hash integration has been working fine for me on 0.2.1, but with 0.3.0 it no longer works as expected. I have the hash integration set up like so:
```
<Router source={hashIntegration()}>
  <App />
</Router>
```

routes:
```
<Routes>
  <Route path="/" element={<div>Home</div>} />
  <Route path="/practice" element={<div>Practice</div>} />
  <Route path="/*all" element={<NotFound />} />
</Routes>
```

and nav links like this:
```
<NavLink
  href="/"
  end
>
  Home
</NavLink>
<NavLink
  href="/practice"
  end
>
  Practice
</NavLink>
```

but when clicked, the nav link navigates to `/#/#/practice` rather than `/#/practice`. This leads to the router not working. Is the usage of hash integration different now in 0.3.0 and the docs haven't been updated yet or is this a bug?

**Comment by rturnq** [comment]
Thanks for the report. We moved link click handlers to a global click handler in 0.3 so we can position ourselves for partial hydration and to support the use of plain anchors. I see the problem and a possible solution so I'll push out a fix this evening.

**Comment by rturnq** [comment]
Fixed in 0.3.1

**Comment by Brendan-csel** [comment]
Testing and is working for me.  Thankyou!

**Comment by fireph** [comment]
working for me 🥰
