### ISSUE TITLE
useParam cannot find my parameter

### ISSUE THREAD

**Issue by MrDesjardins** [solidjs/solid-app-router#88]
# Description

I have a route defined like this one: `"/single-exercise/:exerciseId"`

It works well for the routing of the pages but when I want to use `useParam` the entry for `.exerciseId` is always undefined.

I tried :
`param.exerciseId`
or
`param.exerciseid`

same result: `undefined`

However, if I change my route to: `"/single-exercise/:id"` I can use without problem: `param.id`

What is odd is that the routing of the page works well regardless of how I name the parameter. The problem targets the `useParam`.

# Repro
There is a small project [here](https://github.com/MrDesjardins/gym-water-app)

[Routing defined here](https://github.com/MrDesjardins/gym-water-app/blob/main/src/App.tsx)
[useParam usedHere](https://github.com/MrDesjardins/gym-water-app/blob/main/src/pages/singleExercise/SingleExercise.tsx#L15)

You can see that it is undefined by adding:
``` 
  createEffect(() => {
    console.log(params.id);
    console.log(params.exerciseId;
    console.log(params.exerciseid);
  });
```

**Comment by rturnq** [comment]
I tried to reproduce the issue but wasn't able to. Here are the steps that I tried:

1. `git clone https://github.com/MrDesjardins/gym-water-app.git`
`npm install`
`npm run dev`
2. Navigate to single exercise list: main/single-exercise
3. Click on one of the exercises
4. Notice exercise data is found and displayed
5. Edit this [line](https://github.com/MrDesjardins/gym-water-app/blob/38408eabbcab0e3861a97a24ea605a1cf441862b/src/pages/routes.ts#L7) by changing `:id` to `:exerciseId`
and this [line](https://github.com/MrDesjardins/gym-water-app/blob/38408eabbcab0e3861a97a24ea605a1cf441862b/src/pages/singleExercise/SingleExercise.tsx#L29) by changing: `params.id` to `params.exerciseId`
6. Repeat steps 2-4 and notice it is still working

Are there some other steps I should try or can you make a minimal reproduction from this: https://codesandbox.io/s/solid-app-router-88-yo94ym

**Comment by MrDesjardins** [comment]
Hi, I am not sure if the problem was with hot-reloading not capturing my change in the `.ts` file or something else. You are right, it is working now. Sorry for the bothering you.
