### ISSUE TITLE
How to group routes on the same level?

### ISSUE THREAD

**Issue by elite174** [solidjs/solid-app-router#90]
Guys, I have a question here.

I want to have the following structure

/signIn page

Should be have common service provider
/routea/...
/routeb/...

/* - 404 page

So the route definition could be the following:

```
const routes = [
  {
   path: 'signIn'
   component: SignInPage
  },
  {
    path: 'routea'
    component: () => <ServiceProvider><Outlet/></ServiceProvider>
    children: [...]
  },
  {
    path: 'routeb'
    component: () => <ServiceProvider><Outlet/></ServiceProvider>,
    children: [...]
  },
  {
    path: '*'
    component: NotFoundPage
  }
]
```

I need `ServiceProvider` to not rerender when I switch from `routea` to `routeb`. How to make it shareable? It's not so clear from docs how the things work.

**Comment by rturnq** [comment]
In this case, you can hoist the `ServiceProvider` up to a shared route with an empty path:

```jsx
const routes = [
  {
   path: 'signIn'
   component: SignInPage
  },
  {
    path: "/",
    component: () => <ServiceProvider><Outlet /></ServiceProvider>,
    children: [
      {
        path: "routea",
        children: [...]
      },
      {
        path: "routeb",
        children: [...]
      }
    ]
  },
  {
    path: '*'
    component: NotFoundPage
  }
]
```

**Comment by elite174** [comment]
Thank you so much! It would be nice to add some information about how the matchers work to the readme.
