### ISSUE TITLE
Any plan to support hash router?

### ISSUE THREAD

**Issue by Liiked** [solidjs/solid-app-router#91]
Wonder how can i use hash router like https://reactrouterdotcom.fly.dev/docs/en/v6/api#hashrouter? Or any plan to support it?

**Comment by rturnq** [comment]
We support hash routing today though the `source` property on the `<Router>` component.

```jsx
import { Router, hashIntegration } from 'solid-app-router'

<Router source={hashIntegration()}><App></Router>
```

Note there is an open issues around it at the moment #89

**Comment by lukaszczernal** [comment]
You just saved my life.

Any plans to add it to the docs? :-)
