### ISSUE TITLE
createEffect is not showing isRouting state

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-app-router#92]
when i am trying to get isRouting status i am only getting false even if routing from Home page to about page

MainLayout.jsx
```
export default function MainLayout() {
  const isRouting = useIsRouting();
 

  createEffect(() => console.log(isRouting()));
  return (
    <div>
      <Navbar />
      <main className="py-14">
          <Show when={!isRouting()} fallback={<Loader />}>
            <Outlet />
          </Show>
      </main>
    </div>
  );
}

```
App.jsx
```
 <Routes>
      <Route path="/" element={<MainLayout />}>
        <Route path="" element={<Home />} />
        <Route path="about" element={<About />} />
      </Route>
 </Routes>


```

**Comment by rturnq** [comment]
The `isRouting` hook just exposes Solid's [transition](https://www.solidjs.com/docs/latest/api#usetransition) pending signal. This means it will only change when the navigation event causes a concurrent transition to go pending which requires a resource to be read within a suspense boundary. The primary use case for this hook is to toggle a loading indicator while a navigation is suspended because of a resource is blocking. In your example, the navigation happens completely synchronously and there is no transition period.

**Comment by harshmangalam** [comment]
can you show me some simple  working example  ?

**Comment by rturnq** [comment]
Here is an example that might help: https://codesandbox.io/s/solid-app-router-92-y044lc

**Comment by harshmangalam** [comment]
@rturnq thanks now i am able to integrate.

**Comment by nomi-san** [comment]
Seems `useIsRouting()` doesn't have reactivity.
This is my trick to show `nprogress` on navigating.

```js
function Loader() {
    const location = useLocation()
    const [path, setPath] = createSignal(location.pathname)

    const Progress = () => {
        onMount(() => {
            nProgress.start()
            setPath(location.pathname)
        })
        onCleanup(() => {
            nProgress.done()
        })
        return <></>
    }

    // Validate with pathname
    return <Show when={location.pathname !== path()}><Progress /></Show>
}
```

**Comment by DanWizard** [comment]
> Seems `useIsRouting()` doesn't have reactivity. This is my trick to show `nprogress` on navigating.
> 
> ```js
> export default function Loader() {
>     const location = useLocation()
>     const [path, setPath] = createSignal(location.pathname)
> 
>     const Progress = () => {
>         if (!isServer) {
>             nProgress.start()
>         }
> 
>         onMount(async () => {
>             nProgress.done()
>             setPath(location.pathname)
>         })
> 
>         return <></>
>     }
> 
>     // Validate with pathname
>     return <Show when={location.pathname !== path()}><Progress /></Show>
> }
> ```

I am just using `useLocation` as a signal seems to work fine

**Comment by nomi-san** [comment]
> I am just using useLocation as a signal seems to work fine

Yesh, now it has true reactivity.
