### ISSUE TITLE
Static routes

### ISSUE THREAD

**Issue by CoolOppo** [solidjs/solid-app-router#95]
How do you include static assets without importing them in JS? Is there a way to set a static asset path?

**Comment by rturnq** [comment]
I think this is really dependent on your server. Generally for SPAs, you need to configure the server to rewrite paths to whichever serves your application (eg `/`) and configure where it looks for static files. This should all take place before a request ever makes it to the application so the router isn't involved.

**Comment by CoolOppo** [comment]
Just realizing now I should have already said this: I'm using Vite with the router. (From the `solidjs/templates/ts-router` template). Is there any way to set it up so that I can reference static paths and have it direct to those assets? I found [this](https://vitejs.dev/guide/build.html#public-base-path), but it's definitely not helping lol. Any ideas?

**Comment by CoolOppo** [comment]
Oh, duh https://vitejs.dev/guide/assets.html#the-public-directory
