### ISSUE TITLE
navigate(path, {replace: true}) with hashIntegration

### ISSUE THREAD

**Issue by Goody-Goody** [solidjs/solid-app-router#96]
We're using hashIntegration in our app, but the {replace: true} option in the navigate function doesn't seem to "replace" the current path in window.history. Is this a work-in-progress?

There doesn't seem to be an equivalent for this [code](https://github.com/solidjs/solid-app-router/blob/99e977b970a31cba31b41e9698c78143afeb43fd/src/integration.ts#L86-L90) in [here](https://github.com/solidjs/solid-app-router/blob/99e977b970a31cba31b41e9698c78143afeb43fd/src/integration.ts#L104-L107)

**Comment by rturnq** [comment]
Thanks for pointing this out. You are right we should be using `location.replace` for replace. Will fix.
