### ISSUE TITLE
Path Base

### ISSUE THREAD

**Issue by DynamicArray** [solidjs/solid-app-router#97]
I have an app delivered from /multiple/nested/path/on/my/server (ie that's base value in my vite config).

But, the public url is {https}/dashboard.

How do I config for lazy loading from the full nested path, but with my links relative to the /dashboard url? (eg /dashboard/sub-page)

**Comment by rturnq** [comment]
It sounds like you have the [public base path](https://vitejs.dev/guide/build.html#public-base-path) in Vite configured as `/multiple/nested/path/on/my/server` meaning you intend to serve your application, JS, CSS and other public assets to the user at `https://my.domain.tld/multiple/nested/path/on/my/server`. However it sounds like you want the user to access your app at `https://my.domain.tld/dashboard`. To put it  another way - when a user goes to `https://my.domain.tld/dashboard` they will get your application index.html and it will contains things like:
```html
<link href="/multiple/nested/path/on/my/server/css/styles.css">
<script src="/multiple/nested/path/on/my/server/js/index.js">
```

I think most of the configuration is going to need to happen on your server. You'll need to rewrite URLs from `/dashboard` to `/multiple/nested/path/on/my/server` so the user's request will go to something. Vite should already take care the import paths for the lazy/code-split components.

For the router's part, there isn't really anything you need to do but as a convenience you can set a base path on the `<Router>` component so you can treat `/dashboard` as `/`.

```jsx
<Router base="dashboard">
```
will let you write
```jsx
<Link href="/sub-page">
```
which will render as
```html
<a href="/dashboard/sub-page">
```

**Comment by ryansolid** [comment]
Closing as stale.

**Comment by aminnairi** [comment]
Is the `base` property for the `Router` documented somewhere? I feel like it's missing in the `README.md`.
